export { editarPartida } from './editar-partida-service/editar-partida-service'
export { deletarPartida } from './deletar-partida-service/deletar-partida-service'
export { criarPartida } from './criar-partida-service/criar-partida-service'
export { getTime } from './buscar-times-service/buscar-times-service'
export { getPartidas } from './buscar-partidas-service/buscar-partidas-service'
export { getLideres } from './buscar-lideres-service/buscar-lideres-esporte-service'
