export { schemaCriacaoPartida } from './schemaCriacaoPartida'
export { schemaEdicaoPartida } from './schemaEdicaoPartida'
export { schemaExcluirPartida } from './schemaExcluirPartida'
export { schemaBuscarTime } from './schemaBuscarTime'
export { schemaBuscarLideres } from './schemaBuscarLideres'
