GET http://localhost:3000/partidas HTTP/1.1
content-type: application/json
###


POST http://localhost:3000/partidas HTTP/1.1
content-type: application/json

{
    "data": "2020/05/05",
    "esporte": "Futebol",
    "casa": {
      "time": "Brasil",
      "pontuacao": 2
    },
    "visitante": {
      "time": "Japão",
      "pontuacao": "5"
  }
}
###


PUT http://localhost:3000/partidas/c46db55d-f462-4740-ac91-7a8f142c0565 HTTP/1.1
content-type: application/json

{
    "esporte": "vôlei",
    "casa": {
      "time": "Imortal Tricolor",
      "pontuacao": 10
    },
    "visitante": {
      "time": "Inter",
      "pontuacao": 0
    }
}
###

PUT http://localhost:3000/time/63879bf7-9e7e-432c-8573-968e9a14952e HTTP/1.1
content-type: application/json

{
    "casa": {
      "pontuacao": "2"
    },
    "visitante": {
      "time": "Alemanha",
      "pontuacao": "2"
    }
}
###

DELETE  http://localhost:3000/partidas/3a0ba8ac-582c-410a-b6b9-83ed11c1543f HTTP/1.1
content-type: application/json

# {
#     "id": "57f4c940-d8d4-4fb4-b4cc-27d0a997b512"
# }