GET http://localhost:3000/partidas HTTP/1.1
content-type: application/json
###


POST http://localhost:3000/partidas HTTP/1.1
content-type: application/json

{
    "visitante": "Internacional",
    "casa": "Grêmio",
    "placarVisitante": 0,
    "placarCasa": 10
}
###


PUT http://localhost:3000/partidas/e9ce00ce-1c8c-4fc5-a33b-a3efb7f5f4ab HTTP/1.1
content-type: application/json

{
    "visitante": "Palmeiras"
}
###


DELETE  http://localhost:3000/partidas/d3406cb7-f986-42c6-b9b8-9e9210a9f7a4 HTTP/1.1
content-type: application/json